import os


ENV_MODE = os.getenv('ENV_MODE')

MONGO_USER = os.getenv('MONGO_USER')
MONGO_PASSWORD = os.getenv('MONGO_PASSWORD')
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES')

AWS_BUCKET_NAME = "tracenote-media"
IAM_ACCESS_KEY = os.getenv('IAM_ACCESS_KEY')
IAM_SECRET_ACCESS_KEY = rf"{os.getenv('IAM_SECRET_ACCESS_KEY')}"